Fix phive installation in CI (#13)
* Fix phive installation in CI

* PATH will contain ~/bin later in CI

* PHPStan need phive to be installed in CI

* Retry on GPG keyserver error in CI

* Separate tests on old PHP

* Define WP_CONTENT_DIR

* Dirty hack to restrict sebastian/comparator

* Raise min phpunit version

* Add missing --prefer-lowest

* Add sebastian/version

* Require only phpunit/phpunit

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -55,10 +55,11 @@ jobs:
       - name: "Install phive from cache"
         run: |
           if [ ! -r "${HOME}/.phive/phive.phar" ]; then
-            mkdir -p ~/bin
+            mkdir -p "${HOME}/bin" "${HOME}/.phive"
             wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
             wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
-            gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=10 --recv-keys 0x9D8A98B29B2D5D79
+            gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79 \
+              || gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79
             if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
               echo "Invalid phive signature" 1>&2
               rm -f "${HOME}/.phive/phive.phar"
@@ -68,7 +69,7 @@ jobs:
           fi
           install --verbose --mode=0755 -T "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"
           echo "::add-path::${HOME}/bin"
-          phive install --trust-gpg-keys C00543248C87FB13,31C7E470E2138192
+          "${HOME}/bin/phive" install --trust-gpg-keys C00543248C87FB13,31C7E470E2138192
 
       - name: "Cache dependencies installed with composer"
         uses: "actions/cache@v2.1.0"
@@ -126,6 +127,32 @@ jobs:
         id: "determine-composer-cache-directory"
         run: "echo \"::set-output name=directory::$(composer config cache-dir)\""
 
+      - name: "Cache PHAR files installed with phive"
+        uses: "actions/cache@v2.1.0"
+        with:
+          path: "${HOME}/.phive"
+          key: "php-${{ matrix.php-version }}-phive-${{ matrix.dependencies }}-${{ hashFiles('.phive/phars.xml') }}"
+          restore-keys: "php-${{ matrix.php-version }}-phive-${{ matrix.dependencies }}-"
+
+      - name: "Install phive from cache"
+        run: |
+          if [ ! -r "${HOME}/.phive/phive.phar" ]; then
+            mkdir -p "${HOME}/bin" "${HOME}/.phive"
+            wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
+            wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
+            gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79 \
+              || gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=30 --recv-keys 0x9D8A98B29B2D5D79
+            if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
+              echo "Invalid phive signature" 1>&2
+              rm -f "${HOME}/.phive/phive.phar"
+              exit 11
+            fi
+            rm "${HOME}/.phive/phive.phar.asc"
+          fi
+          install --verbose --mode=0755 -T "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"
+          echo "::add-path::${HOME}/bin"
+          "${HOME}/bin/phive" install --trust-gpg-keys C00543248C87FB13,31C7E470E2138192
+
       - name: "Cache dependencies installed with composer"
         uses: "actions/cache@v2.1.0"
         with:
@@ -171,13 +198,63 @@ jobs:
           - "7.4"
           - "7.3"
           - "7.2"
+
+        dependencies:
+          - "lowest"
+          - "locked"
+          - "highest"
+
+    steps:
+      - name: "Checkout"
+        uses: "actions/checkout@v2.3.2"
+
+      - name: "Install PHP with extensions"
+        uses: "shivammathur/setup-php@2.4.1"
+        with:
+          coverage: "none"
+          extensions: "${{ env.PHP_EXTENSIONS }}"
+          php-version: "${{ matrix.php-version }}"
+
+      - name: "Determine composer cache directory"
+        id: "determine-composer-cache-directory"
+        run: "echo \"::set-output name=directory::$(composer config cache-dir)\""
+
+      - name: "Cache dependencies installed with composer"
+        uses: "actions/cache@v2.1.0"
+        with:
+          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
+          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
+          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"
+
+      - name: "Install lowest dependencies from composer.json"
+        if: "matrix.dependencies == 'lowest'"
+        run: "composer require --no-interaction --no-progress --no-suggest --prefer-lowest --dev 'phpunit/phpunit:^6.5 || ^7.5'"
+
+      - name: "Install locked dependencies from composer.lock"
+        if: "matrix.dependencies == 'locked'"
+        run: "composer install --no-interaction --no-progress --no-suggest"
+
+      - name: "Install highest dependencies from composer.json"
+        if: "matrix.dependencies == 'highest'"
+        run: "composer update --no-interaction --no-progress --no-suggest"
+
+      - name: "Run integration tests with phpunit/phpunit"
+        run: "cp -f src/dbless-wpdb.php wordpress/wp-content/db.php && vendor/bin/phpunit --colors=always"
+
+  tests-old:
+    name: "Tests on unsupported PHP"
+
+    runs-on: "ubuntu-latest"
+
+    strategy:
+      matrix:
+        php-version:
           - "7.1"
           - "7.0"
           - "5.6"
 
         dependencies:
           - "lowest"
-          - "locked"
           - "highest"
 
     steps:
