PHPStan need phive to be installed in CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -126,6 +126,31 @@ jobs:
         id: "determine-composer-cache-directory"
         run: "echo \"::set-output name=directory::$(composer config cache-dir)\""
 
+      - name: "Cache PHAR files installed with phive"
+        uses: "actions/cache@v2.1.0"
+        with:
+          path: "${HOME}/.phive"
+          key: "php-${{ matrix.php-version }}-phive-${{ matrix.dependencies }}-${{ hashFiles('.phive/phars.xml') }}"
+          restore-keys: "php-${{ matrix.php-version }}-phive-${{ matrix.dependencies }}-"
+
+      - name: "Install phive from cache"
+        run: |
+          if [ ! -r "${HOME}/.phive/phive.phar" ]; then
+            mkdir -p "${HOME}/bin" "${HOME}/.phive"
+            wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
+            wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
+            gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=10 --recv-keys 0x9D8A98B29B2D5D79
+            if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
+              echo "Invalid phive signature" 1>&2
+              rm -f "${HOME}/.phive/phive.phar"
+              exit 11
+            fi
+            rm "${HOME}/.phive/phive.phar.asc"
+          fi
+          install --verbose --mode=0755 -T "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"
+          echo "::add-path::${HOME}/bin"
+          "${HOME}/bin/phive" install --trust-gpg-keys C00543248C87FB13,31C7E470E2138192
+
       - name: "Cache dependencies installed with composer"
         uses: "actions/cache@v2.1.0"
         with:
